import {login,currentUser,logout,canWrite,canDelete} from "./js/auth.js";
import {loadPatients,savePatients,createPatient,deletePatient,resetPatients,getPatient} from "./js/patients.js";
import {processFiles} from "./js/documents.js";
import {comparePrescriptions,prescriptionText} from "./js/prescriptions.js";
import {getTimeline} from "./js/timeline.js";
import {stats} from "./js/dashboard.js";

const app=document.querySelector("#app");let user=currentUser();let patients=loadPatients();let selectedId=null;let activeTab="overview";

function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function fmtBytes(n){if(!n)return "";return n<1024?n+" B":n<1048576?(n/1024).toFixed(1)+" KB":(n/1048576).toFixed(1)+" MB"}
function initials(n){return n.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase()}
function refresh(){patients=loadPatients();render()}
function render(){user=currentUser();if(!user)return renderLogin();renderApp()}
function renderLogin(){app.innerHTML=`<div class="login-shell"><div class="login-card"><div class="brand"><div class="brand-icon">MD</div><div><h1>Medical Document Intelligence</h1><p>Patient Timeline • Review 3 Prototype</p></div></div><h2>Welcome back</h2><p class="muted">Sign in to manage patient medical records.</p><form id="loginForm"><div class="field"><label>Email</label><input id="email" type="email" required placeholder="name@demo.com"></div><div class="field"><label>Password</label><input id="password" type="password" required placeholder="Password"></div><button class="primary" style="width:100%">Login</button><div id="loginError"></div></form><div class="demo-box"><b>Demo accounts</b><br>Admin: admin@demo.com / Admin@123<br>Doctor: doctor@demo.com / Doctor@123<br>Viewer: viewer@demo.com / Viewer@123</div></div></div>`;document.querySelector("#loginForm").onsubmit=e=>{e.preventDefault();const s=login(email.value,password.value);if(!s){loginError.innerHTML='<div class="error">Invalid email or password.</div>'}else{selectedId=null;activeTab="overview";render()}}}
function renderApp(){const s=stats(patients);app.innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-icon">MD</div><div><h1>Medical Document Intelligence</h1><p>Patient Timeline System</p></div></div><div class="user-area"><span class="username">${esc(user.name)}</span><span class="role">${esc(user.role)}</span><button class="secondary" id="logoutBtn">Logout</button></div></header><div class="layout"><aside class="sidebar"><button class="side-btn ${!selectedId?"active":""}" data-nav="dashboard">📊 Dashboard</button><button class="side-btn" data-nav="patients">👥 Patients</button>${canWrite(user)?'<button class="side-btn" data-nav="new">➕ New Patient</button>':""}</aside><main class="content">${selectedId?patientView():dashboardView(s)}</main></div></div>`;document.querySelector("#logoutBtn").onclick=()=>{logout();render()};document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{if(b.dataset.nav==="new"){openPatientModal();return}selectedId=null;render()});wireCurrent()}
function dashboardView(s){return `<div class="page-title"><div><h2>Dashboard</h2><p class="muted">Multi-user, multi-patient medical record workspace</p></div></div><div class="grid stats"><div class="card"><div class="stat-label">Patients</div><div class="stat-value">${s.patients}</div></div><div class="card"><div class="stat-label">Documents</div><div class="stat-value">${s.documents}</div></div><div class="card"><div class="stat-label">Prescriptions</div><div class="stat-value">${s.prescriptions}</div></div><div class="card"><div class="stat-label">Lab records</div><div class="stat-value">${s.labs}</div></div></div><div class="card" style="margin-top:16px"><div class="page-title"><h2 style="font-size:18px">Patient Management</h2>${canWrite(user)?'<button class="primary" id="newPatientBtn">Create Patient</button>':""}</div><div class="toolbar"><input class="search" id="patientSearch" placeholder="Search by patient name or Patient ID..."></div><div id="patientGrid" class="grid patient-grid">${patientCards(Object.values(patients))}</div></div><div class="card" style="margin-top:16px"><b>Access level</b><p class="muted small">${user.role==="Admin"?"Full administrative access including patient deletion and demo reset.":user.role==="Doctor"?"Clinical access: upload, process and view patient records.":"Read-only access: view documents, analysis and timeline."}</p>${user.role==="Admin"?'<button class="danger" id="resetBtn">Reset Demo Data</button>':""}</div>`}
function patientCards(list){if(!list.length)return '<div class="empty">No patients found.</div>';return list.map(p=>`<div class="card patient-card"><div class="patient-head"><div class="avatar">${initials(p.name)}</div><span class="pill">${esc(p.id)}</span></div><h3>${esc(p.name)}</h3><p class="muted">${p.age} years • ${esc(p.gender)}</p><p class="small">${p.documents?.length||0} documents • ${p.prescriptions?.length||0} prescriptions</p><button class="primary openPatient" data-id="${esc(p.id)}">Open Patient</button></div>`).join("")}
function wireCurrent(){const search=document.querySelector("#patientSearch");if(search)search.oninput=()=>{const q=search.value.toLowerCase();document.querySelector("#patientGrid").innerHTML=patientCards(Object.values(patients).filter(p=>p.name.toLowerCase().includes(q)||p.id.toLowerCase().includes(q)));wirePatientCards()};wirePatientCards();document.querySelector("#newPatientBtn")?.addEventListener("click",openPatientModal);document.querySelector("#resetBtn")?.addEventListener("click",()=>{if(confirm("Reset all local demo data? Uploaded browser data will be removed.")){resetPatients();selectedId=null;render()}})}
function wirePatientCards(){document.querySelectorAll(".openPatient").forEach(b=>b.onclick=()=>{selectedId=b.dataset.id;activeTab="overview";render()})}

function patientView(){const p=getPatient(selectedId);if(!p){selectedId=null;return dashboardView(stats(patients))}const tabs=[["overview","Overview"],["documents","Documents"],["analysis","Analysis"],["prescriptions","Prescriptions"],["comparison","Rx Comparison"],["labs","Lab History"],["timeline","Timeline"]];return `<div class="card"><div class="profile-header"><div class="avatar">${initials(p.name)}</div><div><h2 style="margin:0">${esc(p.name)}</h2><p class="muted" style="margin:5px 0">${esc(p.id)} • ${p.age} years • ${esc(p.gender)}</p></div><div class="profile-actions"><button class="secondary" id="backPatients">← Patients</button>${canDelete(user)?'<button class="danger" id="deletePatient">Delete</button>':""}</div></div></div><div class="tabs">${tabs.map(([id,label])=>`<button class="tab ${activeTab===id?"active":""}" data-tab="${id}">${label}</button>`).join("")}</div>${tabContent(p)}</div>`}
function tabContent(p){switch(activeTab){case"documents":return documentsTab(p);case"analysis":return analysisTab(p);case"prescriptions":return prescriptionsTab(p);case"comparison":return comparisonTab(p);case"labs":return labsTab(p);case"timeline":return timelineTab(p);default:return overviewTab(p)}}
function overviewTab(p){return `<div class="grid two-col"><div class="card"><h3>Clinical Summary</h3><p><b>Conditions:</b> ${p.conditions?.length? p.conditions.map(esc).join(", "):"No conditions extracted"}</p><p><b>Recent illness:</b> ${p.illnesses?.length?p.illnesses.map(esc).join(", "):"No illness recorded"}</p><p><b>Doctors:</b> ${p.doctors?.length?p.doctors.map(esc).join(", "):"No doctors detected"}</p></div><div class="card"><h3>Record counts</h3><p>Documents: <b>${p.documents?.length||0}</b></p><p>Prescriptions: <b>${p.prescriptions?.length||0}</b></p><p>Lab records: <b>${p.labs?.length||0}</b></p><p>Timeline events: <b>${getTimeline(p).length}</b></p></div></div><div class="card" style="margin-top:16px"><h3>How this prototype analyzes documents</h3><p class="muted">PDF text is extracted in-browser with PDF.js when available. Text/CSV files use FileReader/text APIs. A rule-based extractor identifies dates, doctors, diagnoses/conditions, medicines and common lab mentions, then stores the results under this Patient ID only.</p></div>`}
function documentsTab(p){return `<div class="grid two-col"><div class="card"><h3>Upload documents</h3>${canWrite(user)?`<div class="dropzone"><p><b>Select multiple medical documents</b></p><p class="muted small">PDF, TXT, CSV and other text-readable files. PDF extraction requires the PDF.js CDN.</p><input id="fileInput" type="file" multiple accept=".pdf,.txt,.csv,.json,.html,text/plain,application/pdf"></div><div id="uploadStatus"></div>`:'<div class="notice">Viewer role is read-only and cannot upload documents.</div>'}</div><div class="card"><h3>Patient binding</h3><p>Every uploaded document is stored with:</p><p class="pill">${esc(p.id)}</p><p class="muted small">Switching patients reloads the selected Patient ID and never uses another patient's document array.</p></div></div><div class="card" style="margin-top:16px"><h3>Documents (${p.documents?.length||0})</h3>${p.documents?.length?p.documents.slice().reverse().map(d=>`<div class="doc-row"><div><div class="doc-name">📄 ${esc(d.name)}</div><div class="doc-meta">${esc(d.type)} • ${fmtBytes(d.size)} • ${new Date(d.date).toLocaleString()}</div></div><span class="pill">${esc(d.status)}</span></div>`).join(""):'<div class="empty">No documents uploaded for this patient.</div>'}</div>`}
function analysisTab(p){return `<div class="grid two-col"><div class="card"><h3>Disease / Condition History</h3>${list(p.conditions)}</div><div class="card"><h3>Recent Illness</h3>${list(p.illnesses)}</div><div class="card"><h3>Doctor History</h3>${list(p.doctors)}</div><div class="card"><h3>Extracted Document Events</h3>${(p.documents||[]).length?p.documents.map(d=>`<div class="doc-row"><div><b>${esc(d.name)}</b><div class="doc-meta">${esc((d.extracted?.conditions||[]).join(", ")||"No condition rule matched")}</div></div></div>`).join(""):'<div class="empty">Analyze a document to populate this section.</div>'}</div></div>`}
function list(a){return a?.length?`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:'<span class="muted">No records yet.</span>'}
function prescriptionsTab(p){return `<div class="card"><h3>Prescription History</h3>${p.prescriptions?.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Doctor</th><th>Medicines</th><th>Source</th></tr></thead><tbody>${p.prescriptions.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.doctor)}</td><td>${esc(prescriptionText(x))}</td><td>${esc(x.source||"")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">No prescriptions found.</div>'}</div>`}
function comparisonTab(p){const rows=comparePrescriptions(p);return `<div class="card"><h3>Prescription Comparison</h3><p class="muted">Changes are calculated chronologically from the prescription records currently associated with this patient.</p>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Added</th><th>Removed</th><th>Source</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${r.added.length?r.added.map(esc).join(", "):"—"}</td><td>${r.removed.length?r.removed.map(esc).join(", "):"—"}</td><td>${esc(r.source||"")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Add at least two prescriptions to compare changes.</div>'}</div>`}
function labsTab(p){return `<div class="card"><h3>Laboratory History</h3>${p.labs?.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Test</th><th>Value</th><th>Reference</th><th>Status</th><th>Source</th></tr></thead><tbody>${p.labs.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(l=>`<tr><td>${esc(l.date)}</td><td>${esc(l.test)}</td><td>${esc(l.value)} ${esc(l.unit)}</td><td>${esc(l.range)}</td><td>${esc(l.status)}</td><td>${esc(l.source)}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">No laboratory records found.</div>'}</div>`}
function timelineTab(p){const t=getTimeline(p);return `<div class="card"><h3>Complete Chronological Medical Timeline</h3><div class="timeline">${t.length?t.map(x=>`<div class="timeline-item"><div class="timeline-date">${esc(x.date)}</div><div class="timeline-title">${esc(x.title)}</div><div class="timeline-text">${esc(x.text)}</div></div>`).join(""):'<div class="empty">No timeline events yet.</div>'}</div></div>`}
function openPatientModal(){app.insertAdjacentHTML("beforeend",`<div class="modal" id="modal"><div class="modal-card"><div class="modal-head"><h3>Create Patient</h3><button class="close" id="closeModal">×</button></div><form id="patientForm"><div class="field"><label>Patient Name</label><input id="pname" required></div><div class="field"><label>Patient ID</label><input id="pid" required placeholder="DEMO-1005"></div><div class="field"><label>Age</label><input id="page" type="number" min="0" required></div><div class="field"><label>Gender</label><select id="pgender" style="width:100%;padding:12px;border:1px solid #d7e0ec;border-radius:10px"><option>Female</option><option>Male</option><option>Other</option></select></div><button class="primary">Create Patient</button></form></div></div>`);closeModal.onclick=()=>document.querySelector("#modal")?.remove();patientForm.onsubmit=e=>{e.preventDefault();try{const p=createPatient({name:pname.value.trim(),id:pid.value.trim().toUpperCase(),age:Number(page.value),gender:pgender.value});document.querySelector("#modal").remove();selectedId=p.id;activeTab="overview";refresh()}catch(err){alert(err.message)}}}
document.addEventListener("click",e=>{const tab=e.target.closest("[data-tab]");if(tab&&selectedId){activeTab=tab.dataset.tab;render();return}if(e.target.id==="backPatients"){selectedId=null;render();return}if(e.target.id==="deletePatient"&&selectedId){const p=getPatient(selectedId);if(confirm(`Delete ${p.name} (${p.id}) and all stored records?`)){deletePatient(selectedId);selectedId=null;render()}}});
document.addEventListener("change",async e=>{if(e.target.id!=="fileInput")return;const files=e.target.files;if(!files?.length)return;const box=document.querySelector("#uploadStatus");box.innerHTML='<div class="notice">Processing documents in the browser…</div>';try{const result=await processFiles(selectedId,files);box.innerHTML='<div class="success">'+result.map(x=>`${esc(x.name)} — ${esc(x.status)}`).join("<br>")+"</div>";patients=loadPatients();setTimeout(render,700)}catch(err){box.innerHTML=`<div class="error">${esc(err.message)}</div>`}});
render();